spring:
  application:
    name: BMI

  config:
    import: classpath:constraints.yml

  doc:
    swagger-ui:
      path: /swagger-ui.html
      operationsSorter: method
      tagsSorter: alpha


server:
  port: 8080